# Using Node.js base image
FROM node:14
# Creating and setting working directory
WORKDIR /usr/src/app
# Installing required dependencies
COPY package*.json ./
RUN npm install
# Copying the application code
COPY helloservice.js ./
# Exposing the port
EXPOSE 3002
# Running the application
CMD ["node", "helloservice.js"]
